import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import Product from '../components/Product'
import Lowlight from '../components/Lowlight'
import People from '../components/People'
import Plans from '../components/plan'
import styles from '../styles/Home.module.css'

const Home =()=> {
  return (
    <>
   <div className='w-screen h-min-screen'>
      <Head>
        <title>{``}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-auto'>
        <div className='lg:w-1/2 m-auto text-center h-auto pt-40 w-full'>
          <div className='w-24 bg-black h-24 flex items-center justify-center rounded-full m-auto pt-4'><Image src='/images/Component 9.svg' width={70} height={70}/></div>
        <h1 className='lg:text-5xl text-6xl font-semibold lg:font-bold py-2'>Welcome to the revolution in reality leads</h1>
        <p className='py-4 lg:text-lg'>The leads are records of human voices, real people expressing the desire to purchase a property 
        <span className='wel_txt'>   Click, listen, purchase, connect & convert.</span></p>
       <div className='flex items-center justify-center my-4 lg:flex-row flex-col'>
         <button className='px-9 p-2 rounded-lg bg-black text-white flex items-center'><i className="fab fa-apple text-3xl pr-2"></i>Download for iOS</button>
         <button className='px-4 p-2 rounded-lg bg-black text-white flex items-center lg:mt-0 mt-4 lg:ml-8'><i className="fab fa-android  text-2xl pr-2"></i>Download for Android</button>
       </div>
       </div> 

         <div className='relative'>
       <div className='w-80 lg:w-96 relative m-auto my-14'>
         <img src="/images/Apple iPhone 11.png" alt="" className='w-full relative z-20'/>
         <div className='absolute top-6 lg:top-8 left-6 lg:left-8 lg:right-9 right-6 bottom-7 z-10 overflow-hidden'>
          <img src="/images/ChatList-White.jpg" alt="" className='absolute left-0 right-0 top-0 bottom-0
           inline-block w-full h-full opacity-100' />
            <img src="/images/LockScreen-Light.jpeg" alt="" className='absolute left-0 right-0 top-0 bottom-0
           inline-block w-full h-full opacity-100 rounded-3xl object-cover xyz duration' />
         </div>
       </div>
          {/* text bolder//////////////// */}
          <div className='w-full flex lg:flex-row flex-col text-section lg:top-80 top-0 lg:absolute relative outline-hidden lg:h-auto h-screen'>
         <div className='w-full lg:w-1/2 text-center overflow-hidden '>
         <h1 className=''>STEP</h1>
         </div>
         <div className='lg:w-1/2 w-full lg:text-right text-center overflow-hidden'>
         <h1 className=''>UP</h1>
         </div>
         </div>
       </div>
       <div className='w-full h-auto py-4'>
      <div className='text-center lg:font-bold text-2xl py-4'> More than 10,000 property experts use it</div>
      <div className='w-full flex justify-around items-center py-4 flex-wrap client'>
        <div><Image src="/images/asgardia dark.png" width={100} height={30}/></div>
        <div><Image src="/images/code-lab dark.png" width={100} height={30}/></div>
        <div><Image src="/images/fox-hub-dark.png" width={50} height={30}/></div>
        <div><Image src="/images/utosia dark.png" width={100} height={30}/></div>
        <div><Image src="/images/lighting dark.png" width={100} height={30}/></div>
      </div>
      </div>
       </div>
        <Product/>
        <People/>
        <Lowlight/>
        <Plans/>
    </div>
  </>
  )
}
export default  Home